[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "pbrt"
version = "0.8.2"
[dependencies]
atom = "0.3.6"
atomic = "0.5.0"
byteorder = "1.3.4"
crossbeam = "0.7.3"
crossbeam-channel = "0.4.3"
hexf = "0.1.0"
image = "0.23.10"
impl_ops = "0.1.1"
lazy_static = "1.4.0"
num = "0.3.0"
num_cpus = "1.13.0"
pbr = "1.0.3"
pest = "2.1.3"
pest_derive = "2.1.0"
ply-rs = "0.1.3"
rayon = "1.4.1"
smallvec = "1.4.2"
structopt = "0.3.19"
strum = "0.19.5"
strum_macros = "0.19.4"
typed-arena = "2.0.1"

[[bin]]
name = "rs_pbrt"
path = "src/bin/rs_pbrt.rs"
